### ISSUE TITLE
Faulty characters in non-english forums

### ISSUE THREAD

**Issue by ser** [GerB/magicogp#3]
Rendering of UTF8 characters is broken in non-English forums
![selection_058](https://user-images.githubusercontent.com/231537/40337783-b18b6016-5d9b-11e8-8998-4f781ee6f449.png)

Previously discussed ```$doc->loadHTML('<?xml encoding="utf-8"?>' . $html);``` does not help.

**Comment by GerB** [comment]
Please make sure you have the latest version from Github. If that does not work for you, please report here: https://www.phpbb.com/customise/db/extension/magicogp/support/topic/185056

Provide both your board URL as well as your language settings (board and user) and the URL you've posted in your screenshot.

I'm locking this to keep all discussion related to this issue centralised on phpBB.com
